export default [
  `<div template:="" i::fetch:embrace="SerSeaEpi.json"> <h2>List of Series ("series" is an array? true)</h2> <ol> <li> <h3>Batman The Series is the no. 0 in your play list.</h3> <ul> <li> <h4>Hjelp! Batman is the no. 0 in series Batman The Series.</h4> <ol> <!-- { "type": "season", "title": "Hjelp! Batman", "episodes": [ "episode_pilot" ] } --> <li>episode #0: episode_pilot produced by DC Comics.</li> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template> </ol> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> <li> <h4>Hjelp! Bat2 is the no. 1 in series Batman The Series.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> <li> <h4>Wat will be is the no. 2 in series Batman The Series.</h4> <ol> <!-- { "type": "season", "title": "Wat will be", "episodes": [ "episode_whatever", "episode_whatever-batman-does" ] } --> <li>episode #0: episode_whatever produced by DC Comics.</li> <!-- { "type": "season", "title": "Wat will be", "episodes": [ "episode_whatever", "episode_whatever-batman-does" ] } --> <li>episode #1: episode_whatever-batman-does produced by DC Comics.</li> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template> </ol> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> <li> <h4>Hjelp! Wat! is the no. 3 in series Batman The Series.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> <template for="season of serie.seasons"> <li> <h4>{{season.title}} is the no. {{#season}} in series {{serie.title}}.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> </template> </ul> </li> <template for="serie of series"> <li> <h3>{{serie.title}} is the no. {{#serie}} in your play list.</h3> <ul> <template for="season of serie.seasons"> <li> <h4>{{season.title}} is the no. {{#season}} in series {{serie.title}}.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template> </li> </template></ul> </li> </template> </stanta> <template> </template> </div>`,
  `<div template:="" i::fetch:embrace="SerSeaEpi.json"> <h2>List of Series ("series" is an array? true)</h2> <ol> <li> <h3>Batman The Series is the no. 0 in your play list.</h3> <ul> <li> <h4>Hjelp! Batman is the no. 0 in series Batman The Series.</h4> <ol> <!-- { "type": "season", "title": "Hjelp! Batman", "episodes": [ "episode_pilot" ] } --> <li>episode #0: episode_pilot produced by DC Comics.</li> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> <li> <h4>Hjelp! Bat2 is the no. 1 in series Batman The Series.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> <li> <h4>Wat will be is the no. 2 in series Batman The Series.</h4> <ol> <!-- { "type": "season", "title": "Wat will be", "episodes": [ "episode_whatever", "episode_whatever-batman-does" ] } --> <li>episode #0: episode_whatever produced by DC Comics.</li> <!-- { "type": "season", "title": "Wat will be", "episodes": [ "episode_whatever", "episode_whatever-batman-does" ] } --> <li>episode #1: episode_whatever-batman-does produced by DC Comics.</li> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> <li> <h4>Hjelp! Wat! is the no. 3 in series Batman The Series.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> <template for="season of serie.seasons"> <li> <h4>{{season.title}} is the no. {{#season}} in series {{serie.title}}.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> </template></ul> </li> <template for="serie of series"> <li> <h3>{{serie.title}} is the no. {{#serie}} in your play list.</h3> <ul> <template for="season of serie.seasons"> <li> <h4>{{season.title}} is the no. {{#season}} in series {{serie.title}}.</h4> <template if="(#season % 2) === 0"> <ol> <template for="episode of season.episodes"> <!-- {{JSON.stringify(season, null, 2)}} --> <li>episode #{{#episode}}: {{episode}} produced by {{producer}}.</li> </template></ol> </template></li> </template></ul> </li> </template></stanta> <template></template></div>`,
  [
    "0Adiv",
    "0ttemplate",
    "0r",
    "0ti",
    "0r",
    "0rfetch",
    "0rembrace",
    "0vSerSeaEpi.json",
    "0T ",
    "0Ah2",
    "0TList of Series (\"series\" is an array? true)",
    "0Bh2",
    "0T ",
    "0Aol",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah3",
    "0TBatman The Series is the no. 0 in your play list.",
    "0Bh3",
    "0T ",
    "0Aul",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0THjelp! Batman is the no. 0 in series Batman The Series.",
    "0Bh4",
    "0T ",
    "0Aol",
    "0T ",
    "0C { \"type\": \"season\", \"title\": \"Hjelp! Batman\", \"episodes\": [ \"episode_pilot\" ] } ",
    "0T ",
    "0Ali",
    "0Tepisode #0: episode_pilot produced by DC Comics.",
    "0Bli",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bol",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0THjelp! Bat2 is the no. 1 in series Batman The Series.",
    "0Bh4",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0TWat will be is the no. 2 in series Batman The Series.",
    "0Bh4",
    "0T ",
    "0Aol",
    "0T ",
    "0C { \"type\": \"season\", \"title\": \"Wat will be\", \"episodes\": [ \"episode_whatever\", \"episode_whatever-batman-does\" ] } ",
    "0T ",
    "0Ali",
    "0Tepisode #0: episode_whatever produced by DC Comics.",
    "0Bli",
    "0T ",
    "0C { \"type\": \"season\", \"title\": \"Wat will be\", \"episodes\": [ \"episode_whatever\", \"episode_whatever-batman-does\" ] } ",
    "0T ",
    "0Ali",
    "0Tepisode #1: episode_whatever-batman-does produced by DC Comics.",
    "0Bli",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bol",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0THjelp! Wat! is the no. 3 in series Batman The Series.",
    "0Bh4",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vseason of serie.seasons",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0T{{season.title}} is the no. {{#season}} in series {{serie.title}}.",
    "0Bh4",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bul",
    "0T ",
    "0Bli",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vserie of series",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah3",
    "0T{{serie.title}} is the no. {{#serie}} in your play list.",
    "0Bh3",
    "0T ",
    "0Aul",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vseason of serie.seasons",
    "0T ",
    "0Ali",
    "0T ",
    "0Ah4",
    "0T{{season.title}} is the no. {{#season}} in series {{serie.title}}.",
    "0Bh4",
    "0T ",
    "0Atemplate",
    "0tif",
    "0v(#season % 2) === 0",
    "0T ",
    "0Aol",
    "0T ",
    "0Atemplate",
    "0tfor",
    "0vepisode of season.episodes",
    "0T ",
    "0C {{JSON.stringify(season, null, 2)}} ",
    "0T ",
    "0Ali",
    "0Tepisode #{{#episode}}: {{episode}} produced by {{producer}}.",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bol",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bli",
    "0T ",
    "0Btemplate",
    "0Bul",
    "0T ",
    "0Bli",
    "0T ",
    "0Btemplate",
    "1T ",
    "0Bstanta",
    "0T ",
    "0Atemplate",
    "1T ",
    "0Btemplate",
    "1T ",
    "0Bdiv"
  ]
]